language: node_js
node_js:
- 12
script:
- yarn
- yarn build
deploy:
  provider: gcs
  key_file: saferinsulin-34e45ba9ba4e.json.enc
  edge: true
  bucket: www.saferinsulin.org
  local-dir: dist
  skip_cleanup: true
  acl: "public-read"
  detect_encoding: true
  cache_control: "public, max-age=31536000"
  on:
    branch: master
    repo: saferinsulin/website
